const fileTypes = {
  image: ["jpg", "png", "avif", "webp", "ico", "svg", "jxl", "wp2", "gif"],
  audio: ["mp3", "wav", "flac", "caf", "ogg", "m4a", "aac"],
  video: ["mp4", "mov", "avi", "webm", "mkv", "flv", "mpv", "m3u8"],
  pdf: ["pdf"],
  archive: ["zip", "tar", "gz"],
  code: [
    "html",
    "css",
    "c",
    "cs",
    "cpp",
    "php",
    "py",
    "js",
    "jsx",
    "tsx",
    "ts",
    "mjs",
    "cjs",
    "rb",
    "json",
    "java",
    "go",
    "r",
    "swift",
    "bat",
    "sh",
    "ps1",
    "wasm",
  ],
  csv: ["csv"],
  text: ["txt", "log"],
  msexcel: ["ods", "xlam", "xlsx", "xls", "xlsb", "xlt", "xltm"],
  mspowerpoint: ["pptx", "ppt", "odp", "pptm"],
  msword: ["doc", "docm", "docx", "dot", "dotm", "dotx", "odt"],
};

export default fileTypes;
