name: Expo Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
          cache: yarn
      - uses: expo/expo-github-action@7.0.3
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
      - run: yarn
      - run: expo publish
